force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <description>used to capture the error logs.</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <description>used to capture the module related to error</description>
    <label>Module</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <description>Used to capture the object name which is erring</description>
    <label>Object</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Trace__c.field-meta.xml
<CustomField>
    <fullName>Trace__c</fullName>
    <description>To capture the detailed trace</description>
    <label>Trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/UtilityClass.cls
/******************************************************************************************
 *  Purpose : Utility Class to use across applications            
 *  Name    : Utility Class
 *  Author  : Asok Kumar Sampath
 *  Date    : 28 Apr 2018
 *  Version : 1.0 
 *  
 *  Modification History
 *  Date         Who         Description  
 *  28 Apr 2018  Asok       Initial version
 ***********************************************************************************************/ 
public Class UtilityClass
{
    /* --------------------------------------------------------------------
    * Author:  Asok Kumar Sampath
    * Date:  29 Apr 2018
    * Param: String, String, String
    * Return:  Error_Log__c
    * Purpose: Method to insert the exceptions occuring during any transactions
    ----------------------------------------------------------------------- */ 
    public static Error_Log__c createErrorLog(String obj, String module, String trace)
    {
        Error_Log__c errLog = new Error_Log__c(); 
        errLog.Object__c = obj;
        errLog.Module__c = module;
        errLog.Trace__c = trace;
        return errLog;  
    }
}