force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <description>used to capture the error logs.</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <description>Used to capture the object name which is erring</description>
    <label>Object</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UtilityClassTest.cls
/******************************************************************************************
 *  Purpose : To create mock test         
 *  Name    : BitCoin_ControllerTest
 *  Author  : Asok Kumar Sampath
 *  Date    : 28 Apr 2018
 *  Version : 1.0 
 *  
 *  Modification History
 *  Date         Who         Description  
 *  28 Apr 2018  Asok       Initial version
 ***********************************************************************************************/ 
@isTest
public Class UtilityClassTest
{
    /* --------------------------------------------------------------------
    * Author:  Asok Kumar Sampath
    * Date:  28 Apr 2018
    * Purpose: To test the error log creation
    ----------------------------------------------------------------------- */ 
    static testMethod void testCreateErrorLog()
    {
		Error_Log__c err = UtilityClass.createErrorLog('Error_Log__c','createErrorLog','Error while testing');
		System.assertEquals('Error_Log__c',err.Object__c);        
    }
}